package exceptionhandling;

public class Array_exception3 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
try {
	int a[]= {10,20,30,40,50};
System.out.println(a[5]);
}
catch(Exception e) {
	System.out.println(e);
}
	}

}
